version: 0.2    
phases:
  install:
    commands:
      - curl -sSL https://dot.net/v1/dotnet-install.sh | bash /dev/stdin --channel STS #Instalar .NET 7.0

  pre_build:
    commands:
    - echo "Iniciando restauración de dependencias del proyecto"
    - dotnet restore #Restaurar dependencias
    - echo "Restauración de dependencias terminada"
  build:
    commands:
      - echo "Iniciando compilación"
      - dotnet build -c Release -o ./publish #Compilar solución en modo Release
      - echo "Compilación correcta"
  post_build:
    commands:
      - echo "Ejecutando pruebas unitarias"
      - dotnet test #Ejecutar pruebas unitarias
artifacts:
    files:
        - '**/*' #Incluir todos los archivos generados durante la compilación
    base-directory: 'publish' #Carpeta donde se encuentran los archivos compilados