version: 0.2

env:
  variables:
    PROJECT: CloudComputingUTN.WebApp

phases:
  install:
    commands:
        - echo "Instalando .NET 7 SDK para compilación"
        - curl -sSL https://dot.net/v1/dotnet-install.sh | bash /dev/stdin --channel STS #Instalar .NET 7.0
  pre_build:
    commands:
    - echo "Iniciando restauración de dependencias del proyecto"
    - dotnet restore #Restaurar dependencias
    - echo "Restauración de dependencias terminada"
  build:
    commands:
      - echo "Iniciando compilación"
      - dotnet build -c Release #Compilar en modo Release
      - echo "Compilación correcta"
      - echo "Ejecutando pruebas unitarias"
      - dotnet test -c Release --logger trx --results-directory ./testresults #Ejecutar pruebas unitarias
  post_build:
    commands:
      - echo "Empezando publicación"
      - dotnet publish -c Release  -r win-x64 -o ./build_output ./${PROJECT}/${PROJECT}.csproj --self-contained true
      - cp Procfile ./build_output
      - cd ./build_output
      - zip ../site.zip *
      - cd ../.
      - zip CloudComputingUTN.zip site.zip aws-windows-deployment-manifest.json
      - cp CloudComputingUTN.zip ./build_output

artifacts:
    site:
        files:
            - 'CloudComputingUTN.zip' #Incluir todos los archivos generados durante la compilación
        base-directory: './build_output' #Carpeta donde se encuentran los archivos compilados
        discard-paths: no

reports:
    CloudComputingUTN:
        file-format: VisualStudioTrx
        files:
            - '**/*'
        base-directory: './testresults'